### ISSUE TITLE
CAN 500k not working

### ISSUE THREAD

**Issue by ArendJan** [saierd/platformio-barth-stg#1]
Hi, 

I'm working with your (very nice) example code, but I'm unable to get the CANbus to work at 500k baud.

I've just changed the ```can::init(can::Baudrate::Rate250k);``` to ```can::init(can::Baudrate::Rate500k);```.

My barth is connected to an ESP32 board and the combination works at 250k, but I want to connect the boards in my car, so it needs to work at 500k. I've also tried 1m, but that also doesn't work.

Do you have any hints on how to get it to work at 500k?

**Comment by saierd** [comment]
Hi,

i am not really sure, i mostly just copied that code from the Barth example mentioned in the header and adjusted it for a current version of the HAL. They all use 250k and I probably never tried anything else ;).

I found this nice calculator for setting up the bit rate, though: http://www.bittiming.can-wiki.info/?CLK=16&SamplePoint=75&ctype=bxCAN&calc=1

The table with the parameters as linked above seem to match the values from the original example best, using a sample point of 75% to get the 11/4 split.

Can you try to use the values from that table for the prescaler and the BTR register and check if that fixes it?

**Comment by ArendJan** [comment]
Hi,
I've used that calculator and tried some things in STM32CubeIDE and with these changes I got it working:
Change ```hcan.Init.Prescaler = 4; ``` to ```hcan.Init.Prescaler = 2;``` (can.cpp: line 33) 
and I've removed the ```set_baudrate()``` function.

Tried it with a Vector CanCase and an ESP32 and no issues.

Thank you!
